version: "3.8"
services:
  postgres:
    container_name: biblioteca_postgres
    image: postgres:16
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=biblioteca
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: